### ISSUE TITLE
How am I supposed to install this thing? :)

### ISSUE THREAD

**Issue by wolframklaeger** [friebetill/obsidian-deepl#2]
I am missing any **instructions**, on how this Obsidian plugin has to be installed. I tried

- download
- unzip
- move to .obsidian/plugins

The plugin appears in Obsidian's list of installed community plugins, but cannot be activated.

Any plans to "officialize" this? I would **love** to have DeepL available inside Obsidian, including automated updates. Probably many others as well.

**Comment by friebetill** [comment]
To install the plugin you have to copy the `main.js`, `styles.css` and `manifest.json` in your plugin folder `VaultFolder/.obsidian/plugins/obsidian-deepl/`. You can find the files at [the release page](https://github.com/friebetill/obsidian-deepl/releases). In the zip file the `main.js` is missing, which is why it did not work.

I already submitted the plugin [to the official plugins](https://github.com/obsidianmd/obsidian-releases/pull/1296) 23 days ago, unfortunately the Obsidian team is a bit overwhelmed with the processing of the plugins. If you like you can leave a like there, maybe it will get a higher priority.

**Comment by wolframklaeger** [comment]
Hey Till, 
thanks a lot for the almost real-time response. Works like a charm now. You don't even need the styles.css file. It's empty anyway. Looks like your plugin is already verified. I left all likes I could. I'm sure, that helps. Just wait a second :)

**Comment by kithairon** [comment]
Hi Till, got my free API key from DeepL and implanted this into the plug-in's settings. Upon trying to translate a few lines I keep getting the response "An unknown error has occured. See console for more details." I looked at the console and found some  issues – see attached screenCap. Tried both settings DeepL API Pro and DeepL Free API (I have the latter) to no avail. Any ideas?
[ScreenCap-deepL Plugin.pdf](https://github.com/friebetill/obsidian-deepl/files/10197729/ScreenCap-deepL.Plugin.pdf)

**Comment by friebetill** [comment]
Hi, thanks for reaching out! I noticed that you only received two warnings and one suggestion in the screenshot, but no error messages. Unfortunately, these are not related to the plugin and therefore not actionable. I have released a new version with improved error logging and would be grateful if you could reproduce the error and send me another screenshot of the error message in the console. This will help me troubleshoot the issue and improve the plugin. Let me know if you have any questions or need further assistance.

**Comment by kithairon** [comment]
@friebetill Thanks for the update. Whatever it was – your plugin works beautifully now. Thanks and good luck for your efforts. :)
